language: python

python:
  - 3.8
  - 3.7
  - 3.6

env:
  - DJANGO="Django>=3.1,<3.2"
  - DJANGO="Django>=3.0,<3.1"

  
install:
  - pip install -U coverage coveralls $DJANGO

script: coverage run -a --source=yadialogs setup.py test

after_success:
  coveralls

